[package]
name = "fsss"
version = "0.0.2"
edition = "2024"
description = "FSS Server"
email = "yassine.bna@proton.me"

[dependencies]
anyhow = { version = "1.0.100", features = ["std"] }
argon2 = "0.5.3"
aws-config = "1.8.12"
aws-sdk-s3 = {version = "1.120.0", features = ["behavior-version-latest"]}
axum = { version = "0.8.8", features = ["multipart", "ws", "macros"] }
axum-extra = { version = "0.12.5", features = ["attachment", "file-stream", "typed-header"] }
bcrypt = "0.18.0"
chrono = { version = "0.4.43", features = ["serde"] }
clap = { version = "4.5.54", features = ["derive", "string"] }
dashmap = { version = "6.1.0", features = ["serde"] }
futures-util = "0.3.31"
minio = "0.3.0"
postgres = "0.19.12"
rand = "0.9.2"
rand_core = "0.9.5"
redis = { version = "1.0.3", features = ["connection-manager", "json", "tokio-comp", "uuid"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
time = { version = "0.3.45", features = ["serde"] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-postgres = { version = "0.7.16", features = ["with-chrono-0_4", "with-uuid-1"] }
tokio-tungstenite = { version = "0.28.0", features = ["url"] }
url = { version = "2.5.8", features = ["serde"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
