CREATE TABLE IF NOT EXISTS tokens (
  id BIGSERIAL REFERENCES users(id) UNIQUE,
  token TEXT NOT NULL,
  creation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expiration_time TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '24 hours'
);
